In [2]:
from evaluation_against_llm_judgments import evaluate_against_llm_judgments

In [4]:
evaluate_against_llm_judgments("bm25", 'openai-gpt-oss-120b')

  method                  llm    snapshot   nDCG@10  nDCG@10_unjudged_removed
0   bm25  openai-gpt-oss-120b  snapshot-1  0.754530                  0.756283
1   bm25  openai-gpt-oss-120b  snapshot-2  0.759282                  0.761288
2   bm25  openai-gpt-oss-120b  snapshot-3  0.762609                  0.764353
3   bm25  openai-gpt-oss-120b         all  0.758807                  0.760641

In [9]:
evaluate_against_llm_judgments("results", 'openai-gpt-oss-120b')

,method,llm,snapshot,nDCG@10,nDCG@10_unjudged_removed
0,results,openai-gpt-oss-120b,snapshot-1,0.947947,0.947947
1,results,openai-gpt-oss-120b,snapshot-2,0.953182,0.953182
2,results,openai-gpt-oss-120b,snapshot-3,0.953394,0.953394
3,results,openai-gpt-oss-120b,all,0.951508,0.951508