In [1]:
from evaluation_against_llm_judgments import evaluate_against_llm_judgments

In [2]:
evaluate_against_llm_judgments("bm25", 'openai-gpt-oss-120b')

  method                  llm    snapshot   nDCG@10  nDCG@10_unjudged_removed
0   bm25  openai-gpt-oss-120b  snapshot-1  0.754530                  0.756283
1   bm25  openai-gpt-oss-120b  snapshot-2  0.759282                  0.761288
2   bm25  openai-gpt-oss-120b  snapshot-3  0.762609                  0.764353
3   bm25  openai-gpt-oss-120b         all  0.758807                  0.760641

In [3]:
evaluate_against_llm_judgments("results/put-to-front", 'openai-gpt-oss-120b')

,method,llm,snapshot,nDCG@10,nDCG@10_unjudged_removed
0,put-to-front,openai-gpt-oss-120b,snapshot-1,0.947947,0.947947
1,put-to-front,openai-gpt-oss-120b,snapshot-2,0.953182,0.953182
2,put-to-front,openai-gpt-oss-120b,snapshot-3,0.953394,0.953394
3,put-to-front,openai-gpt-oss-120b,all,0.951508,0.951508

In [4]:
evaluate_against_llm_judgments("results/kq-rm3", 'openai-gpt-oss-120b')

   method                  llm    snapshot   nDCG@10  nDCG@10_unjudged_removed
0  kq-rm3  openai-gpt-oss-120b  snapshot-1  0.711955                  0.842908
1  kq-rm3  openai-gpt-oss-120b  snapshot-2  0.694926                  0.844971
2  kq-rm3  openai-gpt-oss-120b  snapshot-3  0.688111                  0.849003
3  kq-rm3  openai-gpt-oss-120b         all  0.698331                  0.845627

In [5]:
evaluate_against_llm_judgments("results/kq-rm3-dirichlet", 'openai-gpt-oss-120b')

,method,llm,snapshot,nDCG@10,nDCG@10_unjudged_removed
0,kq-rm3-dirichlet,openai-gpt-oss-120b,snapshot-1,0.432830,0.842996
1,kq-rm3-dirichlet,openai-gpt-oss-120b,snapshot-2,0.416876,0.837851
2,kq-rm3-dirichlet,openai-gpt-oss-120b,snapshot-3,0.392074,0.836780
3,kq-rm3-dirichlet,openai-gpt-oss-120b,all,0.413927,0.839209

In [6]:
evaluate_against_llm_judgments("results/kq-rm3-pl2", 'openai-gpt-oss-120b')

,method,llm,snapshot,nDCG@10,nDCG@10_unjudged_removed
0,kq-rm3-pl2,openai-gpt-oss-120b,snapshot-1,0.749276,0.836258
1,kq-rm3-pl2,openai-gpt-oss-120b,snapshot-2,0.740602,0.837117
2,kq-rm3-pl2,openai-gpt-oss-120b,snapshot-3,0.731657,0.838401
3,kq-rm3-pl2,openai-gpt-oss-120b,all,0.740512,0.837259